### ISSUE TITLE
Docker is not working

### ISSUE THREAD

**Issue by IlyaShkurenko** [KoljaB/RealtimeSTT#110]
Spent whole day to try this run by different ways and with no one had success. Always some errors. 
Here is the docker error python3: can't open file '/app/example_browserclient/server.py': [Errno 2] No such file or directory

**Comment by IlyaShkurenko** [comment]
Also receive this error once I said something
Say something...
Traceback (most recent call last):
  File "/Users/illiashkurenko/.pyenv/versions/3.10.11/lib/python3.10/site-packages/RealtimeSTT/tests/simple_test.py", line 6, in <module>
    while (True): print(recorder.text(), end=" ", flush=True)
  File "/Users/illiashkurenko/.pyenv/versions/3.10.11/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 893, in text
    return self.transcribe()
  File "/Users/illiashkurenko/.pyenv/versions/3.10.11/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 844, in transcribe
    status, result = self.parent_transcription_pipe.recv()
  File "/Users/illiashkurenko/.pyenv/versions/3.10.11/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/illiashkurenko/.pyenv/versions/3.10.11/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/illiashkurenko/.pyenv/versions/3.10.11/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**Comment by KoljaB** [comment]
Docker support was a PR, I have no clue about Linux. The EOFError seems to hint to the child process responsible for transcription might have terminated unexpectedly, closing the pipe before the parent process could read from it. I'd test faster_whisper installation separately first. Might create an exception in the transcribe method.

**Comment by IlyaShkurenko** [comment]
so how I can run it or from what this error depends on since someone don't have it?

**Comment by IlyaShkurenko** [comment]
I was able to run It in cloud but anyway thanks for help.

Also do the increasing of resources like GPU, CPU, RAM affects? 

I had 2 GPU, 8vCPU(4 core) 30GB memory
then I changed to 4 GPU, 16vCPU(8 code) 60 GB memory and I didn't receive any changes in performance. fullSentence using large-v2 is coming after 2-3 seconds for a phrase with 20-25 words.

Is there a way how I can speed up it to 0.5-1 second? 

P.S.
Thanks for a good job!

**Comment by KoljaB** [comment]
The number of GPUs should not have any affect. The one thing that really speeds it up is CUDA being available for the torch installation (you can check with torch.cuda.is_available()). In this case transcription time even with large-v2 should be WAY below 1 second for the small chunks we provide here.
