### ISSUE TITLE
"unable to open slave" possible hardware errors or warnings prevent running of project / simple_test.py

### ISSUE THREAD

**Issue by Dainah-0xdeadc0de** [KoljaB/RealtimeSTT#121]
Should note I'm on AMD hardware.
Not sure if the project is talking to my hardware correctly.

I get this at the beginning of running simple test.
```
ALSA lib pcm_dsnoop.c:567:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2722:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2722:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2722:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:404:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:404:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_a52.c:1036:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:481:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:481:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```

Which leads to the following
```

/run/media/dainah/Data/GITHUB/RealtimeSTT-0.2.42/venv/lib/python3.12/site-packages/torch/hub.py:293: UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
[2024-09-30 09:23:44.679] [ctranslate2] [thread 35881] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.
Downloading: "https://github.com/snakers4/silero-vad/zipball/master" to /home/dainah/.cache/torch/hub/master.zip
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 22. Discarding old audio chunks.
Traceback (most recent call last):
  File "/run/media/dainah/Data/GITHUB/RealtimeSTT-0.2.42/tests/simple_test.py", line 8, in <module>
    print(recorder.text(), end=" ", flush=True)
          ^^^^^^^^^^^^^^^
  File "/run/media/dainah/Data/GITHUB/RealtimeSTT-0.2.42/RealtimeSTT/audio_recorder.py", line 1177, in text
    self.wait_audio()
  File "/run/media/dainah/Data/GITHUB/RealtimeSTT-0.2.42/RealtimeSTT/audio_recorder.py", line 1035, in wait_audio
    if self.start_recording_event.wait(timeout=0.02):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

**Comment by realyukii** [comment]
is this issue the same as https://github.com/KoljaB/RealtimeSTT/issues/11 ?

**Comment by KoljaB** [comment]
RealtimeSTT depends on the faster-whisper library, which in turn uses CTranslate2. . It's creator Guillaume Klein says [here](https://github.com/SYSTRAN/faster-whisper/issues/162#issuecomment-1514767030) that AMD is not officially supported in CTranslate2. [Here](https://github.com/SYSTRAN/faster-whisper/issues/515) is an issue from faster-whisper repo that says it might be possible to enable these backends by compiling CTranslate2 from the source with the desired backend before installing faster-whisper.

So - if I got this right - this would mean for MPS acceleration you would first compile CTranslate2 with the necessary backend support (MPS enabled). Then proceed with the installation of RealtimeSTT - which installs faster-whisper, but this should not override the manually compiled version of CTranslate2.

I'd also check if portaudio is installed (apt-get install -y portaudio19-dev). Also on some systems the input device does not get detected correctly and has to be set manually using input_device_index parameter. [This](https://github.com/KoljaB/Linguflex/blob/main/show_devices.py) script lists all devices and can help with finding the correct input device for recording.
