### ISSUE TITLE
GPU running stops at downloading 

### ISSUE THREAD

**Issue by Yaffa16** [KoljaB/RealtimeSTT#127]
I keep getting this error while using the dicker for Gpu : 

==========
== CUDA ==
==========
CUDA Version 12.4.1
Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
Starting server, please wait...
Initializing RealtimeSTT...
Exception in thread Thread-2 (_transcription_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RealtimeSTT/audio_recorder.py", line 862, in _transcription_worker
    worker.run()
  File "/app/RealtimeSTT/audio_recorder.py", line 124, in run
    system_signal.signal(system_signal.SIGINT, system_signal.SIG_IGN)
  File "/usr/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
[2024-10-08 11:59:29.057] [ctranslate2] [thread 153] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.
/usr/local/lib/python3.10/dist-packages/torch/hub.py:293: UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/snakers4/silero-vad/zipball/master" to /root/.cache/torch/hub/master.zip

**Comment by Yaffa16** [comment]
The program gets stuck at the downloading and does not move ahead

**Comment by Chonlasitsk** [comment]
I encounters same issue it seem like now, It can't initiate instance of AudioToTextRecorder() class 
this is error message when I try initiate instance:
```bash
Traceback (most recent call last):
  File "/home/tawan/.pyenv/versions/miniconda3-latest/envs/STT-browser/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tawan/.pyenv/versions/miniconda3-latest/envs/STT-browser/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tawan/.pyenv/versions/miniconda3-latest/envs/STT-browser/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 862, in _transcription_worker
    worker.run()
  File "/home/tawan/.pyenv/versions/miniconda3-latest/envs/STT-browser/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 124, in run
    system_signal.signal(system_signal.SIGINT, system_signal.SIG_IGN)
  File "/home/tawan/.pyenv/versions/miniconda3-latest/envs/STT-browser/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```

**Comment by KoljaB** [comment]
Thanks for reporting. I wasn't aware of signal causing issues in another thread on other platforms. Fixed in current [repo code](https://github.com/KoljaB/RealtimeSTT/blob/master/RealtimeSTT/audio_recorder.py), release for pypi (pip install) coming later.
