### ISSUE TITLE
ImportError: cannot import name 'BatchedInferencePipeline' from 'faster_whisper'

### ISSUE THREAD

**Issue by karayakar** [KoljaB/RealtimeSTT#167]
I have followed instructions and trying to install WSL2 windows
 
 getting below error. 

 from RealtimeSTT import AudioToTextRecorder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxxxxx/realtimetts/RealtimeSTT/RealtimeSTT/__init__.py", line 1, in <module>
    from .audio_recorder import AudioToTextRecorder
  File "/home/karayakar/realtimetts/RealtimeSTT/RealtimeSTT/audio_recorder.py", line 37, in <module>
    from faster_whisper import WhisperModel, BatchedInferencePipeline
ImportError: cannot import name 'BatchedInferencePipeline' from 'faster_whisper' (/home/xxxxx/realtimetts/RealtimeSTT/venv/lib/python3.10/site-packages/faster_whisper/__init__.py)
>>>

any help greatly appreciated.

**Comment by KoljaB** [comment]
Please try again with v0.3.92, some dependecies were wrong (still old faster_whisper version). Thank you for reporting this!
