### ISSUE TITLE
Cannot run example browerclient

### ISSUE THREAD

**Issue by hieuminh65** [KoljaB/RealtimeSTT#29]
## I have error when use the example of browser client folder:

```bash
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/hieunguyenminh/opt/anaconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/hieunguyenminh/opt/anaconda3/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/hieunguyenminh/CODE ALL/TalkToListen/STT-VAD/venv/lib/python3.9/site-packages/RealtimeSTT/audio_recorder.py", line 985, in _recording_worker
    while (self.audio_queue.qsize() >
  File "/Users/hieunguyenminh/opt/anaconda3/lib/python3.9/multiprocessing/queues.py", line 126, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
```

- I tried python 3.11 and 3.9 but they both has this. I wonder what version do you use that have this qsize() supported?
- I want to make an app that connect client and server, what example do you recommend?

Thank you for creating this app, this helps me a lot!

**Comment by KoljaB** [comment]
Seems like mac os, which has some issues with multiprocessing queue size handling. I'll implement a workaround in the next release. 

You can try uncommenting [this block](https://github.com/KoljaB/RealtimeSTT/blob/master/RealtimeSTT/audio_recorder.py#L985-L995) in audio_recorder.py for a quick fix:

```python
while (self.audio_queue.qsize() >
	   self.allowed_latency_limit):

	if not queue_overflow_logged:
		logging.warning("Audio queue size exceeds latency "
						"limit. Current size: "
						f"{self.audio_queue.qsize()}. "
						"Discarding old audio chunks."
						)
		queue_overflow_logged = True
	data = self.audio_queue.get()
```
