### ISSUE TITLE
Simple test not working

### ISSUE THREAD

**Issue by BorretSquared** [KoljaB/RealtimeSTT#30]
Hi, I'm trying to use this library but for me it doesnt seem to be working, I have suspicions that it is because of me installing the gpu variant, but not fully because the last step cudnn is installed does not have an installer on windows. Here is the error I get when running it:

Say something...
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\rober\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\RealtimeSTT\audio_recorder.py", line 578, in _transcription_worker
    transcription = " ".join(seg.text for seg in segments)
  File "C:\Users\rober\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\RealtimeSTT\audio_recorder.py", line 578, in <genexpr>
    transcription = " ".join(seg.text for seg in segments)
  File "C:\Users\rober\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\faster_whisper\transcribe.py", line 508, in generate_segments
    encoder_output = self.encode(segment)
  File "C:\Users\rober\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\faster_whisper\transcribe.py", line 767, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: Library cublas64_12.dll is not found or cannot be loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rober\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\RealtimeSTT\audio_recorder.py", line 581, in _transcription_worker
    except faster_whisper.WhisperError as e:
AttributeError: module 'faster_whisper' has no attribute 'WhisperError'
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\rober\RealtimeSTT\tests\realtimestt_test.py", line 6, in <module>
    while (True): print(recorder.text(), end=" ", flush=True)
  File "C:\Users\rober\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\RealtimeSTT\audio_recorder.py", line 825, in text
    return self.transcribe()
  File "C:\Users\rober\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\RealtimeSTT\audio_recorder.py", line 777, in transcribe
    status, result = self.parent_transcription_pipe.recv()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

**Comment by KoljaB** [comment]
See if you can find the cublas64_11.dll, create a copy in the same folder and name it cublas64_12.dll.

**Comment by KoljaB** [comment]
Btw you can find a cuDNN Installer for Windows [here](https://developer.nvidia.com/rdp/cudnn-archive)

**Comment by BorretSquared** [comment]
Thank you for the quick response, this worked!
