### ISSUE TITLE
Multiprocessing issue on macOS

### ISSUE THREAD

**Issue by PotatoMa0119** [KoljaB/RealtimeSTT#33]
Hi,

Thank you for your great work! I am running 0.1.11 with Python 3.10 on latest macOS, and I am getting this error when running simple_test.py, which is similar to #7 and #29 

Could you please share any workaround for this? Great thanks!

`Say something...
RealTimeSTT: root - ERROR - Unhandled exeption in _recording_worker: 
Exception in thread Thread-1 (_recording_worker):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 994, in _recording_worker
    while (self.audio_queue.qsize() >
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 126, in qsize
    return self._maxsize - self._sem._semlock._get_value()`

**Comment by KoljaB** [comment]
Please remove the while loop in AudioToTextRecorder.py from lines 994 to 1004, this should fix it.

**Comment by PotatoMa0119** [comment]
> Please remove the while loop in AudioToTextRecorder.py from lines 994 to 1004, this should fix it.

Great thanks for the quick reply! But it raises another issue:

> Say something...
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Traceback (most recent call last):
  File "/Users/.../Downloads/RealtimeSTT/simple_test.py", line 6, in <module>
    while (True): print(recorder.text(), end=" ", flush=True)
  File "/Users/...Downloads/RealtimeSTT/RealtimeSTT/audio_recorder.py", line 832, in text
    return self.transcribe()
  File "/Users/.../Downloads/RealtimeSTT/RealtimeSTT/audio_recorder.py", line 784, in transcribe
    status, result = self.parent_transcription_pipe.recv()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

I found that #7 mentioned the same error. Could you please offer some idea on how to fix this?🙏

**Comment by KoljaB** [comment]
Seems pytorch related, I use torch.multiprocessing: please look [here](https://github.com/pytorch/pytorch/issues/78490) and [here](https://stackoverflow.com/questions/53014306/error-15-initializing-libiomp5-dylib-but-found-libiomp5-dylib-already-initial).

I found the suggested solution to be:
- install all packages without MKL support
 `conda install nomkl`  
 
- and then use  
  `conda install numpy scipy pandas tensorflow`  
  
- followed by
  `conda remove mkl mkl-service`

Never saw this one and sorry, I have no Mac. Hope it helps...

**Comment by PotatoMa0119** [comment]
Bypassed the OMP error by running `export KMP_DUPLICATE_LIB_OK=TRUE` in command line, but the EOFError remains... Will keep investigating.

**Comment by triitaoj** [comment]
This took some time to figure out. Instead of using the `KMP_DUPLICATE_LIB_OK=TRUE` workaround, resolve the problem with the duplicate dynamic libraries instead (would be of course better that people managing the packages would solve this):

1. Using Python 3.11, virtualenv, and pip for package management (for conda, the logic probably is the same - need to just figure out where the libs are installed)
2. Assuming a directory structure: `/Users/yourname/RealtimeSTT` (and this is also your present working dir)
3. Create a virtual environment, for example under the local copy of the repo: `$ python -m venv venv`
4. Activate the virtual environment: `$ source venv/bin/activate`
5. Verify that there's no packages at this point: `$ pip freeze` should show empty
6. Install the requirements: `$ pip install RealtimeSTT`
7. Take a look at how many copies of `libiomp5.dylib` are installed at this point:
```
$ find /Users/yourname/RealtimeSTT -name "libiomp5.dylib"
/Users/yourname/RealtimeSTT/venv/lib/python3.11/site-packages/torch/lib/libiomp5.dylib
/Users/yourname/RealtimeSTT/venv/lib/python3.11/site-packages/ctranslate2/.dylibs/libiomp5.dylib
/Users/yourname/RealtimeSTT/venv/lib/python3.11/site-packages/functorch/.dylibs/libiomp5.dylib
```
8. Problem: there's two too much. Let's remove the `torch` and `functorch` ones, and replace them with a symbolic link pointing to `ctranslate2`'s version:
```
# Remove
$ rm /Users/yourname/RealtimeSTT/venv/lib/python3.11/site-packages/functorch/.dylibs/libiomp5.dylib
$ rm /Users/yourname/RealtimeSTT/venv/lib/python3.11/site-packages/torch/lib/libiomp5.dylib

# Replace with symlinks
$ ln -s /Users/yourname/RealtimeSTT/venv/lib/python3.11/site-packages/ctranslate2/.dylibs/libiomp5.dylib /Users/yourname/RealtimeSTT/venv/lib/python3.11/site-packages/functorch/.dylibs/libiomp5.dylib
$ ln -s /Users/yourname/RealtimeSTT/venv/lib/python3.11/site-packages/ctranslate2/.dylibs/libiomp5.dylib /Users/yourname/RealtimeSTT/venv/lib/python3.11/site-packages/torch/lib/libiomp5.dylib
```
Note: You need to use full paths when symlinking.
Note: Replace `yourname` with the home directory name of your OSX.
Note: Now would be a good time to unset the workaround: `unset KMP_DUPLICATE_LIB_OK` if it's set.
10. Should work now
