### ISSUE TITLE
Launches but does not display any text

### ISSUE THREAD

**Issue by Denintendator** [KoljaB/RealtimeSTT#50]
Just spinner with text "speak now". Tried large-v3, small and tiny models, no difference. Mic working well, I just tested it by recording audio using python. It's probably trying, because CPU is heavily loaded, but there's no result.

MacOS Sonoma 14.4

There are no errors in console, just warning:
[2024-04-24 23:53:30.031] [ctranslate2] [thread 8069444] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.

**Comment by KoljaB** [comment]
This warning can be ignored, must be some other issue. The thing is, sometimes some libraries I use (mostly WebRTCVad) don't throw errors (or log any other information) if they don't detect anything like voice activity or wakewords (also when something is wrong with the inputs), so hard to detect. Can't do much to verify too with realtime chunks too. 

The pipeline is: 
Microphone recording -> PvPorcupine Wakeword detection -> WebRTCVad -> SileroVAD -> Whisper
All last 4 can fail.  WebRTCVad (and SileroVAD) often don't log much, WebRTCVad also sensible towards incoming chunks. PvPorcupine is rarely used and logs bit better. Whisper would tell you if something was off.

Please try this as first lines of your script:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

Then create AudioToTextRecorder object with
recorder = AudioToTextRecorder(level=logging.DEBUG)

This sets highest loglevel for all used libs. Maybe you can then see anything in the logging why it fails (sometimes yes, sometimes not - if not you basically have to test every single lib for its own).

**Comment by Denintendator** [comment]
Thanks for answer. I tried and I got this:
`DEBUG:torio._extension.utils:Loading FFmpeg6
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File ".../.venv/lib/python3.12/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(.../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg6.so, 0x0006): Library not loaded: @rpath/libavutil.58.dylib
  Referenced from: <126DCB6D-A04F-381E-9269-B53E8E35F26A> .../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg6.so
  Reason: tried: '/usr/lib/libavutil.58.dylib' (no such file, not in dyld cache)
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File ".../.venv/lib/python3.12/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/.../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg6.so, 0x0006): Library not loaded: @rpath/libavutil.58.dylib
  Referenced from: <126DCB6D-A04F-381E-9269-B53E8E35F26A> .../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg6.so
  Reason: tried: '/usr/lib/libavutil.58.dylib' (no such file, not in dyld cache)
DEBUG:torio._extension.utils:Loading FFmpeg5
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
DEBUG:torio._extension.utils:Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File ".../.venv/lib/python3.12/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(.../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg5.so, 0x0006): Library not loaded: @rpath/libavutil.57.dylib
  Referenced from: <20BD953E-E821-312C-A431-E77499CC9FF6> .../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg5.so
  Reason: tried: '/usr/lib/libavutil.57.dylib' (no such file, not in dyld cache)
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File ".../.venv/lib/python3.12/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(.../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg5.so, 0x0006): Library not loaded: @rpath/libavutil.57.dylib
  Referenced from: <20BD953E-E821-312C-A431-E77499CC9FF6> .../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg5.so
  Reason: tried: '/usr/lib/libavutil.57.dylib' (no such file, not in dyld cache)
DEBUG:torio._extension.utils:Loading FFmpeg4
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
DEBUG:torio._extension.utils:Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File ".../.venv/lib/python3.12/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(.../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg4.so, 0x0006): Library not loaded: @rpath/libavutil.56.dylib
  Referenced from: <F0621199-F06C-332D-AC1D-7E589CAC73E5> .../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg4.so
  Reason: tried: '/usr/lib/libavutil.56.dylib' (no such file, not in dyld cache)
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File ".../.venv/lib/python3.12/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(.../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg4.so, 0x0006): Library not loaded: @rpath/libavutil.56.dylib
  Referenced from: <F0621199-F06C-332D-AC1D-7E589CAC73E5> .../.venv/lib/python3.12/site-packages/torio/lib/libtorio_ffmpeg4.so
  Reason: tried: '/usr/lib/libavutil.56.dylib' (no such file, not in dyld cache)
DEBUG:torio._extension.utils:Loading FFmpeg
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
DEBUG:torio._extension.utils:Failed to load FFmpeg extension.
Traceback (most recent call last):
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.12/site-packages/torio/_extension/utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.`

Seems like it's trying different versions of ffmpeg, but can't find the lib. And there is no any lib in "/usr/lib" related to ffmpeg, while ffmpeg is definitely installed, "ffmpeg -version" outputs:
`ffmpeg version 7.0 Copyright (c) 2000-2024 the FFmpeg developers
built with Apple clang version 15.0.0 (clang-1500.3.9.4)
configuration: --prefix=/usr/local/Cellar/ffmpeg/7.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopenvino --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100`

Kind of weird problem. I didn't find anything like it on the Internet.

**Comment by rajaiswal** [comment]
@Denintendator running into the same issue, were you able to find a solution to this?

**Comment by rihp** [comment]
also found this issue, @rajaiswal did you get around fixing it?

running on a macbook M1 chip

**Comment by M4a1x** [comment]
I tried looking into this issue a bit. 

Based on my findings the errors are generated by torchaudio/torio. It is trying to load ffmpeg binaries from the system when it is `import`ed by `silero_vad`. I would say this behaviour is expected if no `ffmpeg` libraries (not CLI) is installed on the system.

Since `ffmpeg` is only an optional dependency of `silero_vad` to load and save audio files and it is not needed for the normal function of it (as it gets loaded successfully - see output) I believe the error can safely be ignored.

In my case, the missing output came from an issue with my microphone. Apparently the indexes start at 1 for the device id parameter (not 0) and Windows can get quite confused by Bluetooth microphones. Playing around with the IDs and unmuting the microphone in the windows settings made it work for me.

Good luck!

**Comment by snoop911** [comment]
I have this issue too..  ffmpeg is installed (ffmpeg -version works from any directory), and pip torchaudio completes successfully (I see the pyd files in the site library), yet the log shows that they don't get loaded.   The only other strange thing I can see from the log is that it seems to download the huggingface whisper model, despite it being located in a "model" subfolder.  

RealTimeSTT: root - INFO - Starting RealTimeSTT
RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
RealTimeSTT: root - DEBUG - Porcupine wake word detection engine initialized successfully
RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torch\_ops.py", line 1357, in load_library
    ctypes.CDLL(path)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torch\_ops.py", line 1357, in load_library
    ctypes.CDLL(path)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torch\_ops.py", line 1357, in load_library
    ctypes.CDLL(path)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\temp\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
RealTimeSTT: root - DEBUG - Starting realtime worker
RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2025-02-16 19:52:45,865 - root - INFO - Initializing faster_whisper main transcription model tiny
2025-02-16 19:52:46,132 - root - INFO - Microphone connected and validated (input_device_index: 1)
2025-02-16 19:52:46,132 - root - DEBUG - Audio recording initialized successfully at 16000 Hz, reading 1024 frames at a time
2025-02-16 19:52:46,215 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2025-02-16 19:52:46,365 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/Systran/faster-whisper-tiny/revision/main HTTP/1.1" 200 1871
[2025-02-16 19:52:46.564] [ctranslate2] [thread 15708] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.
2025-02-16 19:52:46,682 - faster_whisper - INFO - Processing audio with duration 00:01.620
2025-02-16 19:52:46,704 - faster_whisper - INFO - VAD filter removed 00:00.000 of audio
2025-02-16 19:52:47,221 - root - DEBUG - _audio_data_worker writing audio data into queue.
2025-02-16 19:52:47,237 - root - DEBUG - Faster_whisper main speech to text transcription model initialized successfully
RealTimeSTT: root - DEBUG - Main transcription model ready
RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2025-02-16 19:52:48,246 - root - DEBUG - _audio_data_worker writing audio data into queue.


In case it helps, I'm instantiating the class this way:
    recorder = AudioToTextRecorder(
        level=logging.DEBUG,
        wake_words="computer",  #porcupine 1.9.5
        language="en", 
        silero_deactivity_detection=False,  #use webrtcvad
        use_microphone=True,
        #input_device_index=1,
        download_root="model",   #specify path to whisper small model
        wakeword_backend='pvporcupine',		
        device='cpu'  #'cpu' or 'cuda'
    )

**Comment by Mudasirhabib123** [comment]
Facing same issue on Macos and solved by 

Install ffmpeg
`brew install ffmpeg`

Find where libavutil is installed

`find /opt/homebrew/ -name "libavutil*.dylib"`

Find libavutil.58 for ffmpeg 6 and set as environment variable by 

`export DYLD_LIBRARY_PATH="/opt/homebrew/Cellar/ffmpeg@6/6.1.2_10/lib:$DYLD_LIBRARY_PATH"`

Than reload
`source ~/.zshrc`

Thats it

**Comment by fjl890** [comment]
我也遇到过类似问题。我做了个 RealtimeSTT 桌面版，自带图形界面，打开就能用，不需要命令行操作。支持中文，拖拽文件转文字。详细看这里：https://github.com/KoljaB/RealtimeSTT/issues/320

**Comment by fjl890** [comment]
I had the same issue — the app launches but no text shows up. The VAD pipeline (WebRTCVad → SileroVAD → Whisper) is tricky to debug when nothing logs anything useful.

I ended up building a **desktop app** around RealtimeSTT with a proper GUI, so you can actually see what's happening. Key differences vs the CLI version:
- 🖥️ **Graphical UI** — you see the recording level, transcription as it happens
- 🎙️ **Real-time** + **file batch mode** — drag in audio/video files too
- 📑 **Export to TXT/SRT**
- 🔧 **One-click install** — no dependencies, no `pip install`, no wheel compilation hell

More details here: https://github.com/KoljaB/RealtimeSTT/issues/320

Curious if this is the kind of thing you were looking for — feedback welcome!
