### ISSUE TITLE
No Internet Connection

### ISSUE THREAD

**Issue by BrokenSpaghetti02** [KoljaB/RealtimeSTT#65]
I have installed the RealtimeSTT but when running a few of the test files, it gave this error:

`RuntimeError: It looks like there is no internet connection and the repo could not be found in the cache (/Users/soumikbarua/.cache/torch/hub)`

I am a little bit confused, so can this be resolved?

**Comment by KoljaB** [comment]
Never encountered this error so far, I have no clue what happens here. faster_whisper would require an internet connection on first start to download the Whisper STT model. VAD components will want to load a model too (Silero and WebRTC) at first run.

If there are any other users experiencing this, please write into this issue. Sometimes installing in a virtual environment can solve some issues with the current venv/pip etc

**Comment by BrokenSpaghetti02** [comment]
i have written this code:

```
from RealtimeSTT import AudioToTextRecorder

with AudioToTextRecorder() as recorder:
    print(recorder.text())
```

then it returns this error:

`RealTimeSTT: root - ERROR - Error initializing Silero VAD voice activity detection engine: It looks like there is no internet connection and the repo could not be found in the cache (/Users/soumikbarua/.cache/torch/hub)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1319, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1365, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1314, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1074, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1018, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1460, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1046, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1317, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/hub.py", line 150, in _parse_repo_info
    with urlopen(f"[https://github.com/{repo_owner}/{repo_name}/tree/main/](https://github.com/%7Brepo_owner%7D/%7Brepo_name%7D/tree/main/)"):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/RealtimeSTT/audio_recorder.py", line 518, in __init__
    self.silero_vad_model, _ = torch.hub.load(
                               ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/hub.py", line 565, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/hub.py", line 206, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/hub.py", line 164, in _parse_repo_info
    raise RuntimeError(
RuntimeError: It looks like there is no internet connection and the repo could not be found in the cache (/Users/soumikbarua/.cache/torch/hub)`

**Comment by KoljaB** [comment]
Download of Silero VAD from torch hub failed. A fix for this is out of scope for me (or RealtimeSTT).
 
Try this minimalized test code in python which should fail too:
 
 ```python
self.silero_vad_model, _ = torch.hub.load(
    repo_or_dir="snakers4/silero-vad",
    model="silero_vad",
    verbose=False,
    onnx=False
)
 ```
 
I don't know why exactly the download fails but it's an issue most probably for [Silero Vad Repo](https://github.com/snakers4/silero-vad) (or maybe torch hub related, hard to say).

**Comment by sauravpratihar** [comment]
I found that I had ssl client certificate issue on python so giving the same error. Fixed by following this: https://stackoverflow.com/a/53310545
