### ISSUE TITLE
How to choose the CUDA version？

### ISSUE THREAD

**Issue by jacobtang** [KoljaB/RealtimeSTT#67]
hello,@KoljaB 
I update the latest RealtimeSTT,but something wrong with the CUDA version for the ctranslate2 in the linux env(ubuntu).

RealTimeSTT: root - ERROR - Error initializing main faster_whisper transcription model: CUDA failed with error the operation cannot be performed in the present state
Traceback (most recent call last):
  File "/home/ubuntu/stt_translate/audio_recorder.py", line 629, in _transcription_worker
    model = faster_whisper.WhisperModel(
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 144, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: CUDA failed with error the operation cannot be performed in the present state

How to choose the CUDA version with the  latest RealtimeSTT？should I  download cuDNN v8.7.0 (November 28th, 2022), for CUDA 11.x"?
thanks!

**Comment by KoljaB** [comment]
Ctranslate2 stopped support for CUDA 11. Please upgrade to CUDA 12. See [here](https://github.com/SYSTRAN/faster-whisper#gpu).

**Comment by jacobtang** [comment]
[2024-06-12 16:16:38.255] [ctranslate2] [thread 30905] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead
the CUDA info：
vcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0
