### ISSUE TITLE
CUDA initialization error on current master

### ISSUE THREAD

**Issue by oddlama** [KoljaB/RealtimeSTT#71]
Hi! While I was trying to develop a PR for the shutdown lockup issue, I noticed that the recent commits on master broke model initialization:

```
RealTimeSTT: root - ERROR - Error initializing main faster_whisper transcription model: CUDA failed with error initialization error
Traceback (most recent call last):
  File "/nix/store/df8n8d04bdfdbwpgccjsaw8sc4hin2pk-python3-3.11.9-env/lib/python3.11/site-packages/RealtimeSTT/audio_recorder.py", line 629, in _transcription_worker
    model = faster_whisper.WhisperModel(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/df8n8d04bdfdbwpgccjsaw8sc4hin2pk-python3-3.11.9-env/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 144, in __init__
    self.model = ctranslate2.models.Whisper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA failed with error initialization error
```

If I leave everything the same and downgrade to v1.1.16 everything works fine. My guess is that this happens because you were previously calling `torch.cuda.is_available()` in each thread which initialized the cuda runtime in that thread. This isn't happening anymore possibly leading the observed error.

**Comment by cankaracelebi** [comment]
please try:
from pytorch_lightning.utilities.memory import is_oom_error
